LANGUAGES = {
    "en": "English", "bn": "বাংলা", "hi": "हिन्दी", "ur": "اردو", "ar": "العربية",
    "es": "Español", "fr": "Français", "de": "Deutsch", "pt": "Português", "ru": "Русский",
    "zh": "简体中文", "ja": "日本語", "ko": "한국어", "tr": "Türkçe", "it": "Italiano",
    "nl": "Nederlands", "vi": "Tiếng Việt", "id": "Bahasa Indonesia", "th": "ไทย", "ms": "Bahasa Melayu",
}

T = {
"en": {"dashboard":"Dashboard","admin":"Admin Panel","vps":"VPS","nodes":"Nodes","users":"Users","create_vps":"Create VPS","logout":"Logout","login":"Login","register":"Register","status":"Status","online":"Online","offline":"Offline","installing":"Installing","ready":"Ready","error":"Error","os":"Operating system","engine":"Engine","resources":"Resources","actions":"Actions","start":"Start","stop":"Stop","restart":"Restart","delete":"Delete","ssh":"SSH / SSHX","save":"Save","language":"Language","cpu":"CPU","ram":"RAM","disk":"Disk","unlimited":"Unlimited","refresh":"Refresh","node_status":"Node status","provisioning":"Provisioning","progress":"Progress","hostname":"Hostname","update":"Auto update","panel_install":"Pterodactyl Panel","change_password":"Change password"},
"bn": {"dashboard":"ড্যাশবোর্ড","admin":"অ্যাডমিন প্যানেল","vps":"VPS","nodes":"নোড","users":"ব্যবহারকারী","create_vps":"VPS তৈরি","logout":"লগআউট","login":"লগইন","register":"রেজিস্টার","status":"স্ট্যাটাস","online":"অনলাইন","offline":"অফলাইন","installing":"ইনস্টল হচ্ছে","ready":"প্রস্তুত","error":"ত্রুটি","os":"অপারেটিং সিস্টেম","engine":"ইঞ্জিন","resources":"রিসোর্স","actions":"অ্যাকশন","start":"স্টার্ট","stop":"স্টপ","restart":"রিস্টার্ট","delete":"ডিলিট","ssh":"SSH / SSHX","save":"সেভ","language":"ভাষা","cpu":"CPU","ram":"RAM","disk":"ডিস্ক","unlimited":"আনলিমিটেড","refresh":"রিফ্রেশ","node_status":"নোড স্ট্যাটাস","provisioning":"প্রভিশনিং","progress":"অগ্রগতি","hostname":"হোস্টনেম","update":"অটো আপডেট","panel_install":"Pterodactyl Panel","change_password":"পাসওয়ার্ড পরিবর্তন"},
"hi": {"dashboard":"डैशबोर्ड","admin":"एडमिन पैनल","vps":"VPS","nodes":"नोड्स","users":"उपयोगकर्ता","create_vps":"VPS बनाएँ","logout":"लॉगआउट","login":"लॉगिन","register":"रजिस्टर","status":"स्थिति","online":"ऑनलाइन","offline":"ऑफलाइन","installing":"इंस्टॉल हो रहा है","ready":"तैयार","error":"त्रुटि","os":"ऑपरेटिंग सिस्टम","engine":"इंजन","resources":"संसाधन","actions":"एक्शन","start":"स्टार्ट","stop":"स्टॉप","restart":"रीस्टार्ट","delete":"डिलीट","ssh":"SSH / SSHX","save":"सेव","language":"भाषा","cpu":"CPU","ram":"RAM","disk":"डिस्क","unlimited":"अनलिमिटेड","refresh":"रीफ्रेश","node_status":"नोड स्थिति","provisioning":"प्रोविजनिंग","progress":"प्रगति","hostname":"होस्टनेम","update":"ऑटो अपडेट","panel_install":"Pterodactyl Panel","change_password":"पासवर्ड बदलें"},
"ur": {"dashboard":"ڈیش بورڈ","admin":"ایڈمن پینل","vps":"VPS","nodes":"نوڈز","users":"صارفین","create_vps":"VPS بنائیں","logout":"لاگ آؤٹ","login":"لاگ اِن","register":"رجسٹر","status":"حالت","online":"آن لائن","offline":"آف لائن","installing":"انسٹال ہو رہا ہے","ready":"تیار","error":"خرابی","os":"آپریٹنگ سسٹم","engine":"انجن","resources":"وسائل","actions":"اعمال","start":"شروع","stop":"روکیں","restart":"دوبارہ شروع","delete":"حذف","ssh":"SSH / SSHX","save":"محفوظ","language":"زبان","cpu":"CPU","ram":"RAM","disk":"ڈسک","unlimited":"لامحدود","refresh":"ریفریش","node_status":"نوڈ حالت","provisioning":"پروویژننگ","progress":"پیش رفت","hostname":"ہوسٹ نام","update":"خودکار اپ ڈیٹ","panel_install":"Pterodactyl Panel","change_password":"پاس ورڈ تبدیل کریں"},
"ar": {"dashboard":"لوحة التحكم","admin":"لوحة الإدارة","vps":"VPS","nodes":"العقد","users":"المستخدمون","create_vps":"إنشاء VPS","logout":"تسجيل الخروج","login":"تسجيل الدخول","register":"تسجيل","status":"الحالة","online":"متصل","offline":"غير متصل","installing":"جارٍ التثبيت","ready":"جاهز","error":"خطأ","os":"نظام التشغيل","engine":"المحرك","resources":"الموارد","actions":"الإجراءات","start":"تشغيل","stop":"إيقاف","restart":"إعادة التشغيل","delete":"حذف","ssh":"SSH / SSHX","save":"حفظ","language":"اللغة","cpu":"المعالج","ram":"الذاكرة","disk":"القرص","unlimited":"غير محدود","refresh":"تحديث","node_status":"حالة العقدة","provisioning":"التجهيز","progress":"التقدم","hostname":"اسم المضيف","update":"تحديث تلقائي","panel_install":"Pterodactyl Panel","change_password":"تغيير كلمة المرور"},
"es": {"dashboard":"Panel","admin":"Administración","vps":"VPS","nodes":"Nodos","users":"Usuarios","create_vps":"Crear VPS","logout":"Salir","login":"Entrar","register":"Registrar","status":"Estado","online":"En línea","offline":"Fuera de línea","installing":"Instalando","ready":"Listo","error":"Error","os":"Sistema operativo","engine":"Motor","resources":"Recursos","actions":"Acciones","start":"Iniciar","stop":"Detener","restart":"Reiniciar","delete":"Eliminar","ssh":"SSH / SSHX","save":"Guardar","language":"Idioma","cpu":"CPU","ram":"RAM","disk":"Disco","unlimited":"Ilimitado","refresh":"Actualizar","node_status":"Estado del nodo","provisioning":"Preparando","progress":"Progreso","hostname":"Nombre de host","update":"Actualización automática","panel_install":"Pterodactyl Panel","change_password":"Cambiar contraseña"},
"fr": {"dashboard":"Tableau de bord","admin":"Administration","vps":"VPS","nodes":"Nœuds","users":"Utilisateurs","create_vps":"Créer un VPS","logout":"Déconnexion","login":"Connexion","register":"Inscription","status":"État","online":"En ligne","offline":"Hors ligne","installing":"Installation","ready":"Prêt","error":"Erreur","os":"Système","engine":"Moteur","resources":"Ressources","actions":"Actions","start":"Démarrer","stop":"Arrêter","restart":"Redémarrer","delete":"Supprimer","ssh":"SSH / SSHX","save":"Enregistrer","language":"Langue","cpu":"CPU","ram":"RAM","disk":"Disque","unlimited":"Illimité","refresh":"Actualiser","node_status":"État du nœud","provisioning":"Provisionnement","progress":"Progression","hostname":"Nom d’hôte","update":"Mise à jour auto","panel_install":"Pterodactyl Panel","change_password":"Changer le mot de passe"},
"de": {"dashboard":"Dashboard","admin":"Adminbereich","vps":"VPS","nodes":"Knoten","users":"Benutzer","create_vps":"VPS erstellen","logout":"Abmelden","login":"Anmelden","register":"Registrieren","status":"Status","online":"Online","offline":"Offline","installing":"Installation","ready":"Bereit","error":"Fehler","os":"Betriebssystem","engine":"Engine","resources":"Ressourcen","actions":"Aktionen","start":"Start","stop":"Stop","restart":"Neustart","delete":"Löschen","ssh":"SSH / SSHX","save":"Speichern","language":"Sprache","cpu":"CPU","ram":"RAM","disk":"Datenträger","unlimited":"Unbegrenzt","refresh":"Aktualisieren","node_status":"Knotenstatus","provisioning":"Bereitstellung","progress":"Fortschritt","hostname":"Hostname","update":"Auto-Update","panel_install":"Pterodactyl Panel","change_password":"Passwort ändern"},
"pt": {"dashboard":"Painel","admin":"Administração","vps":"VPS","nodes":"Nós","users":"Utilizadores","create_vps":"Criar VPS","logout":"Sair","login":"Entrar","register":"Registar","status":"Estado","online":"Online","offline":"Offline","installing":"A instalar","ready":"Pronto","error":"Erro","os":"Sistema operativo","engine":"Motor","resources":"Recursos","actions":"Ações","start":"Iniciar","stop":"Parar","restart":"Reiniciar","delete":"Eliminar","ssh":"SSH / SSHX","save":"Guardar","language":"Idioma","cpu":"CPU","ram":"RAM","disk":"Disco","unlimited":"Ilimitado","refresh":"Atualizar","node_status":"Estado do nó","provisioning":"Provisionamento","progress":"Progresso","hostname":"Hostname","update":"Atualização automática","panel_install":"Pterodactyl Panel","change_password":"Alterar palavra-passe"},
"ru": {"dashboard":"Панель","admin":"Админ-панель","vps":"VPS","nodes":"Узлы","users":"Пользователи","create_vps":"Создать VPS","logout":"Выйти","login":"Войти","register":"Регистрация","status":"Статус","online":"Онлайн","offline":"Офлайн","installing":"Установка","ready":"Готов","error":"Ошибка","os":"ОС","engine":"Движок","resources":"Ресурсы","actions":"Действия","start":"Запуск","stop":"Стоп","restart":"Перезапуск","delete":"Удалить","ssh":"SSH / SSHX","save":"Сохранить","language":"Язык","cpu":"CPU","ram":"RAM","disk":"Диск","unlimited":"Без ограничений","refresh":"Обновить","node_status":"Состояние узла","provisioning":"Создание","progress":"Прогресс","hostname":"Имя хоста","update":"Автообновление","panel_install":"Pterodactyl Panel","change_password":"Изменить пароль"},
"zh": {"dashboard":"仪表板","admin":"管理面板","vps":"VPS","nodes":"节点","users":"用户","create_vps":"创建 VPS","logout":"退出","login":"登录","register":"注册","status":"状态","online":"在线","offline":"离线","installing":"安装中","ready":"就绪","error":"错误","os":"操作系统","engine":"引擎","resources":"资源","actions":"操作","start":"启动","stop":"停止","restart":"重启","delete":"删除","ssh":"SSH / SSHX","save":"保存","language":"语言","cpu":"CPU","ram":"内存","disk":"磁盘","unlimited":"无限制","refresh":"刷新","node_status":"节点状态","provisioning":"部署中","progress":"进度","hostname":"主机名","update":"自动更新","panel_install":"Pterodactyl Panel","change_password":"修改密码"},
"ja": {"dashboard":"ダッシュボード","admin":"管理パネル","vps":"VPS","nodes":"ノード","users":"ユーザー","create_vps":"VPSを作成","logout":"ログアウト","login":"ログイン","register":"登録","status":"状態","online":"オンライン","offline":"オフライン","installing":"インストール中","ready":"準備完了","error":"エラー","os":"OS","engine":"エンジン","resources":"リソース","actions":"操作","start":"開始","stop":"停止","restart":"再起動","delete":"削除","ssh":"SSH / SSHX","save":"保存","language":"言語","cpu":"CPU","ram":"RAM","disk":"ディスク","unlimited":"無制限","refresh":"更新","node_status":"ノード状態","provisioning":"プロビジョニング","progress":"進捗","hostname":"ホスト名","update":"自動更新","panel_install":"Pterodactyl Panel","change_password":"パスワード変更"},
"ko": {"dashboard":"대시보드","admin":"관리 패널","vps":"VPS","nodes":"노드","users":"사용자","create_vps":"VPS 생성","logout":"로그아웃","login":"로그인","register":"회원가입","status":"상태","online":"온라인","offline":"오프라인","installing":"설치 중","ready":"준비됨","error":"오류","os":"운영체제","engine":"엔진","resources":"리소스","actions":"작업","start":"시작","stop":"중지","restart":"재시작","delete":"삭제","ssh":"SSH / SSHX","save":"저장","language":"언어","cpu":"CPU","ram":"RAM","disk":"디스크","unlimited":"무제한","refresh":"새로고침","node_status":"노드 상태","provisioning":"프로비저닝","progress":"진행률","hostname":"호스트 이름","update":"자동 업데이트","panel_install":"Pterodactyl Panel","change_password":"비밀번호 변경"},
"tr": {"dashboard":"Kontrol Paneli","admin":"Yönetici Paneli","vps":"VPS","nodes":"Düğümler","users":"Kullanıcılar","create_vps":"VPS Oluştur","logout":"Çıkış","login":"Giriş","register":"Kayıt","status":"Durum","online":"Çevrimiçi","offline":"Çevrimdışı","installing":"Kuruluyor","ready":"Hazır","error":"Hata","os":"İşletim sistemi","engine":"Motor","resources":"Kaynaklar","actions":"İşlemler","start":"Başlat","stop":"Durdur","restart":"Yeniden başlat","delete":"Sil","ssh":"SSH / SSHX","save":"Kaydet","language":"Dil","cpu":"CPU","ram":"RAM","disk":"Disk","unlimited":"Sınırsız","refresh":"Yenile","node_status":"Düğüm durumu","provisioning":"Hazırlanıyor","progress":"İlerleme","hostname":"Ana makine adı","update":"Otomatik güncelleme","panel_install":"Pterodactyl Panel","change_password":"Parolayı değiştir"},
"it": {"dashboard":"Dashboard","admin":"Pannello admin","vps":"VPS","nodes":"Nodi","users":"Utenti","create_vps":"Crea VPS","logout":"Esci","login":"Accedi","register":"Registrati","status":"Stato","online":"Online","offline":"Offline","installing":"Installazione","ready":"Pronto","error":"Errore","os":"Sistema operativo","engine":"Motore","resources":"Risorse","actions":"Azioni","start":"Avvia","stop":"Arresta","restart":"Riavvia","delete":"Elimina","ssh":"SSH / SSHX","save":"Salva","language":"Lingua","cpu":"CPU","ram":"RAM","disk":"Disco","unlimited":"Illimitato","refresh":"Aggiorna","node_status":"Stato nodo","provisioning":"Provisioning","progress":"Progresso","hostname":"Nome host","update":"Aggiornamento automatico","panel_install":"Pterodactyl Panel","change_password":"Cambia password"},
"nl": {"dashboard":"Dashboard","admin":"Beheer","vps":"VPS","nodes":"Nodes","users":"Gebruikers","create_vps":"VPS maken","logout":"Uitloggen","login":"Inloggen","register":"Registreren","status":"Status","online":"Online","offline":"Offline","installing":"Installeren","ready":"Gereed","error":"Fout","os":"Besturingssysteem","engine":"Engine","resources":"Bronnen","actions":"Acties","start":"Start","stop":"Stop","restart":"Herstart","delete":"Verwijderen","ssh":"SSH / SSHX","save":"Opslaan","language":"Taal","cpu":"CPU","ram":"RAM","disk":"Schijf","unlimited":"Onbeperkt","refresh":"Vernieuwen","node_status":"Nodestatus","provisioning":"Provisioning","progress":"Voortgang","hostname":"Hostnaam","update":"Automatische update","panel_install":"Pterodactyl Panel","change_password":"Wachtwoord wijzigen"},
"vi": {"dashboard":"Bảng điều khiển","admin":"Quản trị","vps":"VPS","nodes":"Nút","users":"Người dùng","create_vps":"Tạo VPS","logout":"Đăng xuất","login":"Đăng nhập","register":"Đăng ký","status":"Trạng thái","online":"Trực tuyến","offline":"Ngoại tuyến","installing":"Đang cài","ready":"Sẵn sàng","error":"Lỗi","os":"Hệ điều hành","engine":"Engine","resources":"Tài nguyên","actions":"Thao tác","start":"Khởi động","stop":"Dừng","restart":"Khởi động lại","delete":"Xóa","ssh":"SSH / SSHX","save":"Lưu","language":"Ngôn ngữ","cpu":"CPU","ram":"RAM","disk":"Ổ đĩa","unlimited":"Không giới hạn","refresh":"Làm mới","node_status":"Trạng thái nút","provisioning":"Đang triển khai","progress":"Tiến trình","hostname":"Tên máy","update":"Tự động cập nhật","panel_install":"Pterodactyl Panel","change_password":"Đổi mật khẩu"},
"id": {"dashboard":"Dasbor","admin":"Panel Admin","vps":"VPS","nodes":"Node","users":"Pengguna","create_vps":"Buat VPS","logout":"Keluar","login":"Masuk","register":"Daftar","status":"Status","online":"Online","offline":"Offline","installing":"Menginstal","ready":"Siap","error":"Kesalahan","os":"Sistem operasi","engine":"Mesin","resources":"Sumber daya","actions":"Aksi","start":"Mulai","stop":"Berhenti","restart":"Mulai ulang","delete":"Hapus","ssh":"SSH / SSHX","save":"Simpan","language":"Bahasa","cpu":"CPU","ram":"RAM","disk":"Disk","unlimited":"Tanpa batas","refresh":"Segarkan","node_status":"Status node","provisioning":"Penyediaan","progress":"Kemajuan","hostname":"Nama host","update":"Pembaruan otomatis","panel_install":"Pterodactyl Panel","change_password":"Ubah kata sandi"},
"th": {"dashboard":"แดชบอร์ด","admin":"แผงผู้ดูแล","vps":"VPS","nodes":"โหนด","users":"ผู้ใช้","create_vps":"สร้าง VPS","logout":"ออกจากระบบ","login":"เข้าสู่ระบบ","register":"สมัคร","status":"สถานะ","online":"ออนไลน์","offline":"ออฟไลน์","installing":"กำลังติดตั้ง","ready":"พร้อม","error":"ข้อผิดพลาด","os":"ระบบปฏิบัติการ","engine":"เอนจิน","resources":"ทรัพยากร","actions":"การทำงาน","start":"เริ่ม","stop":"หยุด","restart":"เริ่มใหม่","delete":"ลบ","ssh":"SSH / SSHX","save":"บันทึก","language":"ภาษา","cpu":"CPU","ram":"RAM","disk":"ดิสก์","unlimited":"ไม่จำกัด","refresh":"รีเฟรช","node_status":"สถานะโหนด","provisioning":"กำลังจัดเตรียม","progress":"ความคืบหน้า","hostname":"ชื่อโฮสต์","update":"อัปเดตอัตโนมัติ","panel_install":"Pterodactyl Panel","change_password":"เปลี่ยนรหัสผ่าน"},
"ms": {"dashboard":"Papan Pemuka","admin":"Panel Pentadbir","vps":"VPS","nodes":"Nod","users":"Pengguna","create_vps":"Cipta VPS","logout":"Log keluar","login":"Log masuk","register":"Daftar","status":"Status","online":"Dalam talian","offline":"Luar talian","installing":"Memasang","ready":"Sedia","error":"Ralat","os":"Sistem operasi","engine":"Enjin","resources":"Sumber","actions":"Tindakan","start":"Mula","stop":"Henti","restart":"Mulakan semula","delete":"Padam","ssh":"SSH / SSHX","save":"Simpan","language":"Bahasa","cpu":"CPU","ram":"RAM","disk":"Cakera","unlimited":"Tanpa had","refresh":"Muat semula","node_status":"Status nod","provisioning":"Penyediaan","progress":"Kemajuan","hostname":"Nama hos","update":"Kemas kini automatik","panel_install":"Pterodactyl Panel","change_password":"Tukar kata laluan"},
}

# Keep missing keys safe: English is always the fallback.
def tr(lang: str, key: str) -> str:
    return T.get(lang, T["en"]).get(key, T["en"].get(key, key))
